services:
  - type: web
    name: puntoparcelas
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate && python manage.py seed_data
    startCommand: gunicorn config.wsgi:application --workers 2 --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: CLOUDINARY_URL
        sync: false
      - key: PANEL_USERNAME
        value: "leonardo"
      - key: PANEL_PASSWORD
        sync: false
      - key: PANEL_EMAIL
        value: "l.valencia@ctpchile.cl"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
