# Generated by Django 5.2.16 on 2026-07-14 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('region', models.CharField(choices=[('metropolitana', 'Región Metropolitana'), ('valparaiso', 'Valparaíso'), ('ohiggins', "O'Higgins"), ('maule', 'Maule'), ('biobio', 'Biobío'), ('araucania', 'La Araucanía'), ('los_rios', 'Los Ríos'), ('los_lagos', 'Los Lagos'), ('aysen', 'Aysén'), ('otro', 'Otra región')], default='metropolitana', max_length=20)),
                ('sector', models.CharField(blank=True, help_text='Ej: Colina, Pirque, Lampa', max_length=120)),
                ('precio', models.BigIntegerField(default=0, help_text='Precio en CLP')),
                ('superficie', models.DecimalField(decimal_places=2, default=0, help_text='Superficie en m²', max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('destacada', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('vendida', 'Vendida')], default='disponible', max_length=15)),
                ('tiene_luz', models.BooleanField(default=False, verbose_name='Luz eléctrica')),
                ('tiene_agua', models.BooleanField(default=False, verbose_name='Agua potable')),
                ('tiene_acceso', models.BooleanField(default=False, verbose_name='Acceso pavimentado')),
                ('vista_privilegiada', models.BooleanField(default=False, verbose_name='Vista privilegiada')),
                ('tiene_cercado', models.BooleanField(default=False, verbose_name='Cercado perimetral')),
                ('tiene_porton', models.BooleanField(default=False, verbose_name='Portón de acceso')),
                ('es_turistico', models.BooleanField(default=False, verbose_name='Uso turístico permitido')),
                ('bosque_nativo', models.BooleanField(default=False, verbose_name='Bosque nativo')),
                ('rol_propio', models.BooleanField(default=False, verbose_name='Rol propio / Escriturado')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['-destacada', 'precio'],
            },
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('ciudad', models.CharField(blank=True, max_length=80)),
                ('texto', models.TextField()),
                ('estrellas', models.PositiveSmallIntegerField(default=5)),
                ('es_placeholder', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='FotoParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='parcelas/')),
                ('principal', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.parcela')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['-principal', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(max_length=30)),
                ('region_interes', models.CharField(blank=True, choices=[('metropolitana', 'Región Metropolitana'), ('valparaiso', 'Valparaíso'), ('ohiggins', "O'Higgins"), ('maule', 'Maule'), ('biobio', 'Biobío'), ('araucania', 'La Araucanía'), ('los_rios', 'Los Ríos'), ('los_lagos', 'Los Lagos'), ('aysen', 'Aysén'), ('otro', 'Otra región')], max_length=20)),
                ('monto_disponible', models.BigIntegerField(blank=True, help_text='Presupuesto aprox CLP', null=True)),
                ('mensaje', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('contactado', 'Contactado'), ('en_proceso', 'En proceso'), ('cerrada', 'Cerrada')], default='nueva', max_length=15)),
                ('notas', models.TextField(blank=True, help_text='Notas internas')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('parcela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='core.parcela')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-creado'],
            },
        ),
    ]
