# Generated by Django 6.0.5 on 2026-07-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='monto_disponible',
        ),
        migrations.AddField(
            model_name='consulta',
            name='como_nos_conociste',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('referido', 'Referido de un amigo'), ('google', 'Google'), ('facebook', 'Facebook'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AddField(
            model_name='consulta',
            name='monto_rango',
            field=models.CharField(blank=True, choices=[('menos_10m', 'Menos de $10.000.000'), ('10m_20m', '$10.000.000 – $20.000.000'), ('20m_35m', '$20.000.000 – $35.000.000'), ('35m_50m', '$35.000.000 – $50.000.000'), ('mas_50m', 'Más de $50.000.000')], max_length=20),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='profesion',
            field=models.CharField(blank=True, default='Inversionista', max_length=80),
        ),
    ]
