# Generated by Django 6.0.5 on 2026-07-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_monto_rango_como_conociste_profesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='region_interes',
            field=models.CharField(blank=True, choices=[('coquimbo', 'Coquimbo'), ('valparaiso', 'Valparaíso'), ('metropolitana', 'Región Metropolitana'), ('ohiggins', "O'Higgins"), ('maule', 'Maule'), ('nuble', 'Ñuble'), ('biobio', 'Biobío'), ('araucania', 'La Araucanía'), ('los_rios', 'Los Ríos'), ('los_lagos', 'Los Lagos'), ('aysen', 'Aysén'), ('otro', 'Otra región')], max_length=20),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='region',
            field=models.CharField(choices=[('coquimbo', 'Coquimbo'), ('valparaiso', 'Valparaíso'), ('metropolitana', 'Región Metropolitana'), ('ohiggins', "O'Higgins"), ('maule', 'Maule'), ('nuble', 'Ñuble'), ('biobio', 'Biobío'), ('araucania', 'La Araucanía'), ('los_rios', 'Los Ríos'), ('los_lagos', 'Los Lagos'), ('aysen', 'Aysén'), ('otro', 'Otra región')], default='metropolitana', max_length=20),
        ),
    ]
