# Generated by Django 6.0.5 on 2026-07-15 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_coquimbo_nuble_regions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('precio_contado', models.BigIntegerField(default=0, help_text='Precio al contado CLP')),
                ('precio_credito', models.BigIntegerField(blank=True, help_text='Total crédito CLP', null=True)),
                ('diferencia', models.BigIntegerField(blank=True, null=True)),
                ('pie', models.BigIntegerField(blank=True, null=True)),
                ('cuota', models.BigIntegerField(blank=True, help_text='Cuota mensual CLP', null=True)),
                ('num_cuotas', models.IntegerField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='core.parcela')),
            ],
            options={
                'verbose_name': 'Plan de Pago',
                'verbose_name_plural': 'Planes de Pago',
                'ordering': ['orden'],
            },
        ),
    ]
