# Generated by Django 5.2.16 on 2026-07-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_parcela_moneda_video_mapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='geo_pdf',
            field=models.FileField(blank=True, help_text='Plano GEO en PDF', upload_to='geo/'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='precio',
            field=models.BigIntegerField(default=0, help_text='Número sin puntos ni comas'),
        ),
    ]
