# Generated by Django 5.2.16 on 2026-07-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_geo_pdf_to_parcela'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='mapa_embed_url',
            field=models.URLField(blank=True, help_text='URL embed de Google Maps (para mostrar el mapa en la web)'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='mapa_url',
            field=models.URLField(blank=True, help_text='URL de Google Maps (link de compartir, para el botón)'),
        ),
    ]
