# Generated by Django 5.2.16 on 2026-07-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='imagen_credito',
            field=models.ImageField(blank=True, help_text='Imagen de valores/financiamiento (crédito). Se muestra individual, NO en la galería. Solo para parcelas que lo ameriten.', upload_to='credito/'),
        ),
    ]
