# Generated by Django 6.0.5 on 2026-08-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_parcela_imagen_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='ga4_id',
            field=models.CharField(blank=True, help_text='Empieza con G- (ej: G-ABC1234567). Lo entrega Google Analytics.', max_length=30, verbose_name='ID de Google Analytics'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='google_verificacion',
            field=models.CharField(blank=True, help_text='Opcional. Solo si Google Search Console lo pide por etiqueta.', max_length=120, verbose_name='Codigo de verificacion de Google'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='meta_pixel_id',
            field=models.CharField(blank=True, help_text='Solo numeros. Lo entrega el Administrador Comercial de Meta.', max_length=30, verbose_name='ID del pixel de Meta'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='meta_verificacion',
            field=models.CharField(blank=True, help_text='El codigo que pide Meta para confirmar que el sitio es tuyo.', max_length=120, verbose_name='Codigo de verificacion de dominio (Meta)'),
        ),
    ]
