# Generated by Django 6.0.5 on 2026-08-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_siteconfig_ga4_id_siteconfig_google_verificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='imagen_compartir',
            field=models.ImageField(blank=True, help_text='La foto que se ve cuando mandas tu sitio por WhatsApp, Instagram o Facebook. Ideal 1200x630 px. Si la dejas vacia se muestra el logo.', upload_to='config/', verbose_name='Imagen al compartir el link'),
        ),
    ]
