# Generated by Django 5.2.17 on 2026-09-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_imagen_compartir'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad/comuna para agrupar por catálogo de ciudad (SEO). Ej: Frutillar', max_length=80),
        ),
        migrations.AddField(
            model_name='parcela',
            name='seo_h1',
            field=models.CharField(blank=True, help_text='Si se deja vacío, se usa el nombre de la parcela.', max_length=200, verbose_name='H1 SEO (opcional)'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Si se deja vacío, se arma automático desde nombre/región/superficie.', max_length=250, verbose_name='Título SEO (opcional)'),
        ),
    ]
