# Generated by Django 5.2.16 on 2026-10-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_seo_ciudades_jorge_22_09'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='cerca_playa',
            field=models.BooleanField(default=False, verbose_name='A menos de 30 min de la playa'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='credito_directo',
            field=models.BooleanField(default=False, verbose_name='Crédito directo / pie cero'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='vista_lago',
            field=models.BooleanField(default=False, verbose_name='Vista al lago'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='vista_mar',
            field=models.BooleanField(default=False, verbose_name='Vista al mar'),
        ),
    ]
